// Generated by CoffeeScript 1.4.0
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function(require) {
  var LoadedView, View;
  View = require('backbone.viewdsl').View;
  LoadedView = (function(_super) {

    __extends(LoadedView, _super);

    function LoadedView() {
      return LoadedView.__super__.constructor.apply(this, arguments);
    }

    LoadedView.prototype.render = function() {
      return this.$el.html('HI');
    };

    return LoadedView;

  })(View);
  return {
    LoadedView: LoadedView
  };
});
